In [ ]:
# 데이터 불러오기
import seaborn as sns # seaborn을 불러오고 SNS로 축약
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder    # LabelEncoder() method를 불러옴
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

iris = sns.load_dataset('iris')  # iris라는 변수명으로 Iris data를 download
X = iris.drop('species', axis=1) # 'species'열을 drop하고 input X를 정의
y = iris['species']
print(np.unique(y))

# y data를 범주형으로 변환
classle = LabelEncoder() # one-hot과 구분해서 사용
y = classle.fit_transform(iris['species'].values) # species 열의 문자열을 categorical 값으로 전환

# 전체 data를 training set과 test set으로 split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=1, stratify=y) #층화추출법
print(X_train.shape, X_test.shape)

['setosa' 'versicolor' 'virginica']
(105, 4) (45, 4)


In [ ]:
# Logistic regression (one-versus-rest)
Logit = LogisticRegression(C=1e2, random_state=1, multi_class = 'ovr')
Logit.fit(X_train, y_train)
y_train_pred = Logit.predict(X_train)
y_test_pred = Logit.predict(X_test)

# Accuracy score
print(accuracy_score(y_test,y_test_pred))    # test accuracy
print(accuracy_score(y_train,y_train_pred))  # train accuracy
print(confusion_matrix(y_test, y_test_pred)) # Confusion matrix

0.9777777777777777
0.9523809523809523
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


In [ ]:
y_test_pred_proba = Logit.predict_proba(X_test)
print('Predicted Classes:', np.around(y_test_pred[:5],3))
print('Predicted Probabilities:', np.around(y_test_pred_proba[0],3))
np.sum(y_test_pred_proba[:5], axis = 1)

Predicted Classes: [2 0 0 1 1]
Predicted Probabilities: [0.    0.081 0.919]


array([1., 1., 1., 1., 1.])

In [ ]:
Z_1 = np.matmul(X_test.iloc[0], np.transpose(Logit.coef_)) + Logit.intercept_
print(Z_1)
print(np.around(sigmoid(Z_1),3))

[-15.577  -2.34    6.973]
[0.    0.088 0.999]


In [ ]:
np.set_printoptions(precision=3)
print(Logit.coef_) #(n_classes, n_features)
print(Logit.fit_intercept)
print(Logit.intercept_)

[[-0.767  2.098 -4.686 -1.909]
 [-1.56  -2.155  1.991 -2.961]
 [-0.799 -4.121  6.23   9.978]]
True
[ 11.741  10.716 -30.653]


In [ ]:
# Logistic regression (multinomial)
Logit1 = LogisticRegression(C=1e2, random_state=1, 
                            multi_class = 'multinomial', max_iter=300)
l_1=Logit1.fit(X_train, y_train)
y_train_pred = Logit1.predict(X_train)
y_test_pred = Logit1.predict(X_test)

# Accuracy score
print(accuracy_score(y_test,y_test_pred))     # test accuracy
print(accuracy_score(y_train,y_train_pred))   # train accuracy
print(confusion_matrix(y_test, y_test_pred))  # Confusion matrix

1.0
0.9809523809523809
[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


In [ ]:
y_test_pred_proba = Logit1.predict_proba(X_test)
print('Predicted Classes:', np.around(y_test_pred[:5],3))
print('Predicted Probabilities:', np.around(y_test_pred_proba[0],3))
np.sum(y_test_pred_proba[:5], axis = 1)

Predicted Classes: [2 0 0 1 1]
Predicted Probabilities: [0.    0.001 0.999]


array([1., 1., 1., 1., 1.])

In [ ]:
Z_2 = np.matmul(X_test.iloc[0,:], np.transpose(Logit1.coef_)) + Logit1.intercept_
print(Z_2)
print(np.around(softmax(Z_2),3))

[-11.682   2.113   9.569]
[0.    0.001 0.999]


In [ ]:
?LogisticRegression

In [ ]:
print(Logit1.coef_) #(n_classes, n_features)
print(Logit1.fit_intercept)
print(Logit1.intercept_)

[[-0.684  2.908 -5.958 -2.678]
 [ 0.745  0.798 -0.197 -4.164]
 [-0.061 -3.705  6.155  6.842]]
True
[ 21.005   5.425 -26.43 ]


In [ ]:
X_train[1]

In [ ]:
def softmax(x):
    e_x = np.exp(x)
    return e_x / e_x.sum()

def sigmoid(x):
    e_x = np.exp(-x)
    return 1 / (1+e_x)