In [ ]:
##5장에서 사용한 iris data 사용
%matplotlib inline    
import matplotlib.pyplot as plt
from sklearn.datasets import make_circles
from sklearn import metrics
from sklearn.svm import SVC 
import seaborn as sns
import numpy as np
from ipywidgets import interact, fixed
from mpl_toolkits import mplot3d

iris=sns.load_dataset('iris') # iris data 불러오기
X=iris.drop('species',axis=1) # 특성변수만으로 구성된 X data Frame 생성
y=iris['species']             # 분류의 목적 변수만으로 구성된 y data Frame생성

from sklearn.preprocessing import LabelEncoder #범주형 변수 숫자로 치환하는 함수 호출
classle=LabelEncoder()
y=classle.fit_transform(iris['species'].values)#범주형 변수 숫자로 치환

from sklearn.model_selection import train_test_split #train set과 test set으로 데이터 나누기 위한 함수 호출
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=123, stratify=y)

from sklearn.preprocessing import StandardScaler #data의 표준화 함수 호출.
sc=StandardScaler()
sc.fit(X_train)
X_train_std=sc.transform(X_train)
X_test_std=sc.transform(X_test)

In [ ]:
#Linear SVM
c_ = [0.1, 1, 5, 10]
for i in range(len(c_)):
  print('Linear SVM with c =',c_[i],':')
  svm=SVC(kernel='linear',C=c_[i],random_state=1)
  svm.fit(X_train,y_train)
  y_train_pred=svm.predict(X_train) 
  y_test_pred=svm.predict(X_test)
  print('Train Acc:',np.around(metrics.accuracy_score(y_train, y_train_pred) ,3))  # Training accuracy
  print('Test Acc:',np.around(metrics.accuracy_score(y_test, y_test_pred),3)) # Test accuracy

Linear SVM with c = 0.1 :
Train Acc: 0.971
Test Acc: 0.956
Linear SVM with c = 1 :
Train Acc: 0.99
Test Acc: 0.978
Linear SVM with c = 5 :
Train Acc: 0.99
Test Acc: 0.933
Linear SVM with c = 10 :
Train Acc: 0.99
Test Acc: 0.933


In [ ]:
print(svm.support_)
print(svm.n_support_)

[ 21  43 101   8  23  33  76  85  27  41  60  95]
[3 5 4]


In [ ]:
metrics.confusion_matrix(y_test,y_test_pred)  #confusion_matrix

array([[15,  0,  0],
       [ 0, 12,  3],
       [ 0,  0, 15]])

In [ ]:

print(metrics.classification_report(y_test,y_test_pred))   #classification_report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.80      0.89        15
           2       0.83      1.00      0.91        15

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45



In [ ]:
#Kernel SVM
c_ = [0.1, 1, 10]
k_ = ['rbf','poly', 'sigmoid']
g_ = [0.1, 1, 10]

for k in range(len(k_)):
  for c in range(len(c_)):
    for g in range(len(g_)):
        print('SVM with kenel=', k_[k], 'c=',c_[c], 'g=',g_[g],':')
        svm=SVC(kernel=k_[k],C=c_[c],gamma = g_[g],random_state=1)
        svm.fit(X_train,y_train)
        y_train_pred=svm.predict(X_train) 
        y_test_pred=svm.predict(X_test)
        print('Train Acc:',np.around(metrics.accuracy_score(y_train, y_train_pred) ,3))  # Training accuracy
        print('Test Acc:',np.around(metrics.accuracy_score(y_test, y_test_pred),3)) # Test accuracy


# 감마가 작을수록 xi와 xj의 거리를 실제보다 멀게 평가하여 과소적합 (큰 감마 과대적합, train acc > test acc => 감마 증가)
# 

# if gamma='scale' (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,
# if ‘auto’, uses 1 / n_features.
#  gamma parameter defines how far the influence of a single training example reaches, with low values meaning 'far' and high values meaning 'close'.
# The gamma parameters can be seen as the inverse of the radius of influence of samples selected by the model as support vectors

SVM with kenel= rbf c= 0.1 g= 0.1 :
Train Acc: 0.943
Test Acc: 0.933
SVM with kenel= rbf c= 0.1 g= 1 :
Train Acc: 0.962
Test Acc: 0.956
SVM with kenel= rbf c= 0.1 g= 10 :
Train Acc: 0.895
Test Acc: 0.756
SVM with kenel= rbf c= 1 g= 0.1 :
Train Acc: 0.981
Test Acc: 0.956
SVM with kenel= rbf c= 1 g= 1 :
Train Acc: 0.981
Test Acc: 0.956
SVM with kenel= rbf c= 1 g= 10 :
Train Acc: 0.99
Test Acc: 0.956
SVM with kenel= rbf c= 10 g= 0.1 :
Train Acc: 0.99
Test Acc: 0.978
SVM with kenel= rbf c= 10 g= 1 :
Train Acc: 0.99
Test Acc: 0.956
SVM with kenel= rbf c= 10 g= 10 :
Train Acc: 1.0
Test Acc: 0.911
SVM with kenel= poly c= 0.1 g= 0.1 :
Train Acc: 0.99
Test Acc: 0.978
SVM with kenel= poly c= 0.1 g= 1 :
Train Acc: 0.99
Test Acc: 0.933
SVM with kenel= poly c= 0.1 g= 10 :
Train Acc: 1.0
Test Acc: 0.978
SVM with kenel= poly c= 1 g= 0.1 :
Train Acc: 0.99
Test Acc: 0.956
SVM with kenel= poly c= 1 g= 1 :
Train Acc: 0.99
Test Acc: 0.978
SVM with kenel= poly c= 1 g= 10 :
Train Acc: 1.0
Test Acc: 0.978
SV

In [ ]:
#Kernel
c_ = [0.1, 1, 5, 10]
for i in range(len(c_)):
  print('Linear SVM with c =',c_[i],':')
  svm=SVC(kernel='linear',C=c_[i],random_state=1)
  svm.fit(X_train,y_train)
  y_train_pred=svm.predict(X_train) 
  y_test_pred=svm.predict(X_test)
  print('Train score :',np.around(metrics.accuracy_score(y_train, y_train_pred) ,3))  # Training accuracy
  print('Test score :',np.around(metrics.accuracy_score(y_test, y_test_pred),3)) # Test accuracy

In [ ]:
metrics.confusion_matrix(y_test,y_test_pred)   #confusion_matrix

array([[15,  0,  0],
       [ 0, 14,  1],
       [ 0,  3, 12]])

In [ ]:
svm=SVC(kernel='sigmoid',C=0.01,gamma = 0.1,random_state=1, decision_function_shape= 'ovr')
svm.fit(X_train,y_train)
y_train_pred=svm.predict(X_train) 
y_test_pred=svm.predict(X_test)
print('Train Acc:',np.around(metrics.accuracy_score(y_train, y_train_pred) ,3))  # Training accuracy
print('Test Acc:',np.around(metrics.accuracy_score(y_test, y_test_pred),3)) # Test accuracy

Train Acc: 0.067
Test Acc: 0.044


In [ ]:
?SVC